import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import logoImg from "../assets/logo.svg";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={montserrat.className}>
        <div className="flex min-h-screen flex-col items-start justify-center">
          <header className="mx-auto w-full max-w-screen-xl py-2">
            <img src={logoImg.src} alt="" />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
